sonar-scanner.bat -D
sonar.projectKey=testing_cvmaker_new
sonar.sources=." -D"
sonar.projectName=testing_cvmaker_new
sonar.projectVersion=1.0
sonar.sources=app,database,config,bootstrap,routes
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_ec17c8eb440d162449e4bdd556e2b7c45a2fe9ad





